### ISSUE TITLE
Nicknames for areas

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/MountainProject#54]
The bot should be able to interpret some hard-coded nicknames. For instance:

- "RRG" = "Red River Gorge"
- "LRC" = "Little Rock City"
- "NRG" = "New River Gorge"
- "HP40" (with or without space) = "Horse Pens 40"
- "LCC" = "Little Cottonwood Canyon"
- "Font" = "Fontainebleau"?
- etc

**Comment by peacheym** [comment]
I believe this would not be a difficult feature to implement provided that there exists a list of these common nicknames.  You would be able to match them directly for unique entries and match to where the problem is for duplicate nicknames.  Let me know if you know where I would find a list like this and I would love to help implement it!

Matt

**Comment by derekantrican** [comment]
I don't think there exists such a list, but there might be a lot of benefit to "crowdsourcing" this. Eg posting to somewhere like the climbing subreddit or MountainProject forums with a spreadsheet asking people to fill in any known area abbreviations

**Comment by derekantrican** [comment]
As far as the code, the best place to change it (going off my memory of the code and without actually investigating) would probably be the `MPObject.NameForMatch` turning it into a list/array of `NamesForMatch`
